### ISSUE TITLE
BOT_TOKEN ERROR

### ISSUE THREAD

**Issue by OlegatorKras** [pininkara/BingChatBot#12]
How to fix it Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\krasi\pythonProject121\bing.py", line 17, in <module>
    print("BOT_TOKEN: " + BOT_TOKEN)
          ~~~~~~~~~~~~~~^~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

**Comment by pininkara** [comment]
you did not set the environment variable correctly，please search how to set  environment variables in PyCharm

**Comment by OlegatorKras** [comment]
Fixed it but whats again it? 
![image](https://user-images.githubusercontent.com/132183281/235336633-2c0fb15e-253a-4c86-8b55-b96039cefa5e.png)
![image](https://user-images.githubusercontent.com/132183281/235336649-72a77105-718a-4a7c-b07a-8c0a60dc1d59.png)

**Comment by pininkara** [comment]
Please fill you digital id like ‘123456,67890’,you can get your digital id by @get_id_bot

**Comment by pininkara** [comment]
And your bot token is leaked, please delete the issue after your problem is solved

**Comment by OlegatorKras** [comment]
![image](https://user-images.githubusercontent.com/132183281/235337328-b2ed638f-772f-4142-b7c7-3a4aeac6a7f2.png)
)Respect you!

**Comment by OlegatorKras** [comment]
Respect
