### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by Mailovskii** [pininkara/BingChatBot#14]
![image](https://user-images.githubusercontent.com/132333972/235596331-71d309db-6353-46bb-ae23-a35cdc204bb9.png)
:(

**Comment by pininkara** [comment]
you did not set the environment variable correctly，please search how to set environment variables

**Comment by Mailovskii** [comment]
> you did not set the environment variable correctly，please search how to set environment variables

I'm not good at python :( What do I need to do?

**Comment by Mailovskii** [comment]
I did everything as written in the thread, inserted the token telegram bot, inserted my telegram idi, inserted cookies in the file with cookies, but error after error appears. If you remove the .split, there will be this:
![image](https://user-images.githubusercontent.com/132333972/235602976-5a52462f-24c9-4925-93ee-f697c4528539.png)
