### ISSUE TITLE
Bot still reply even I set Group Mode = False

### ISSUE THREAD

**Issue by Am1nCmd** [pininkara/BingChatBot#15]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/15339573/236730433-745dfa4e-92e7-4a3a-88d4-57f09b4f8ad5.png">
<img width="893" alt="image" src="https://user-images.githubusercontent.com/15339573/236730540-61a21988-f0a3-44e8-af66-25ef916cbdfe.png">

It should be reply only on Mention or in private chat

**Comment by pininkara** [comment]
Please make sure you set the BOT_ID

**Comment by Am1nCmd** [comment]
I already did it the second screenshot

On 8 May 2023, at 10.59, 捏捏卡™ ***@***.******@***.***>> wrote:



Please make sure you set the BOT_ID

**Comment by pininkara** [comment]
This may be a bug, I will fix it soon

**Comment by Am1nCmd** [comment]
K, waiting for an update, thx in advance

On 8 May 2023, at 11.10, 捏捏卡™ ***@***.******@***.***>> wrote:



This may be a bug, I will fix it soon

**Comment by pininkara** [comment]
I fixed it in the latest version, please update and redeploy . Thanks for your help.

**Comment by Am1nCmd** [comment]
alright, let me try

**Comment by Am1nCmd** [comment]
great one, it is working now.

a little bit to improve:
- make bot reply when we reply to their message bubble

like
1st-time chat we mention @bot, then the bot reply, then we reply again to the bot to continue the conversation in a group, <currently bot ignores the message>
it should reply too 
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/15339573/236757599-2c6d8442-08e3-4ba6-ae27-7df21affff80.png">
<img width="512" alt="image" src="https://user-images.githubusercontent.com/15339573/236756842-edac0328-df01-4e0f-90f7-f8edff3b6807.png">

**Comment by pininkara** [comment]
Thanks for your advice，I will implement it in the future

**Comment by pininkara** [comment]
I have completed this function, thank you for your help
