### ISSUE TITLE
python requirements

### ISSUE THREAD

**Issue by kamil-malinski** [pininkara/BingChatBot#6]
Hi!

I'm running Ubuntu 22.04 and having a hart time to fullfill all the python requirements defined in requirement.txt

Some modules doesn't seem to be available in the required version for Ubuntu 22.04

What distribution do you recommend to fullfill all the requirements?

Kamil

**Comment by onuratakan** [comment]
The requirements are not set true, there is many garbage requirement i will send a pr for this.
